#!/bin/bash
DIR=$1
mkdir -p $HOME/.gitkraken/

if [ ! -f $HOME/.gitconfig ]; then
  touch $HOME/.gitconfig
fi

docker run --name gitkraken -ti --rm \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /dev:/dev \
  -e DISPLAY=$DISPLAY \
  -v $DIR/:/home/user/dev \
  -v $HOME/.gitkraken/:/home/user/.gitkraken/ \
  -v $HOME/.gitconfig:/home/user/.gitconfig \
  -e UID=`id -u` -e GID=`id -g` \
  -v ~/.ssh/:/home/user/.ssh/ \
  --privileged \
  siredmar/gitkraken:latest
